using Xamarin.SourceWriter;

namespace Java.Interop.Tools.BindingsGenerator;

static class CodeWriterExtensions
{
	public static void WriteAutoGeneratedHeader (this CodeWriter writer)
	{
		writer.WriteLine ("//------------------------------------------------------------------------------");
		writer.WriteLine ("// <auto-generated>");
		writer.WriteLine ("//     This code was generated by a tool.");
		writer.WriteLine ("//");
		writer.WriteLine ("//     Changes to this file may cause incorrect behavior and will be lost if");
		writer.WriteLine ("//     the code is regenerated.");
		writer.WriteLine ("// </auto-generated>");
		writer.WriteLine ("//------------------------------------------------------------------------------");
		writer.WriteLine ();

		writer.WriteLine ($"#nullable restore");
		writer.WriteLine ();
	}
}
